apiVersion: v1
kind: Pod
metadata:
  name: cosbench-pod
  namespace: cosbench-project
spec:
  securityContext:
    fsGroup: 2000
  serviceAccountName: default
  containers:
  - name: cosbench
    image: quay.io/parikshith/noobaa  #need to push image to qe repo
    envFrom:
      - configMapRef:
          name: cosbench-config
    ports:
      - containerPort: 18088

